name: C/C++ CI

on:
  push:
    branches: [master, valueclass]
    paths:
      - 'src/**'
      - 'include/**'

  pull_request:
    branches: [master]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Notify start to irc-gitlama
    steps:
      - name: Extract Branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: IRC notification
        uses: Gottox/irc-message-action@v1
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GitHub
          message: |-
            ${{ github.actor }} started a build of ${{ github.event.repository.name }}-[${{ steps.extract_branch.outputs.branch }}]

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++, clang++]

    steps:
      - uses: actions/checkout@v2
      - name: Install Build Environment
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install pkg-config autoconf-archive
             else
                brew upgrade;
                brew install pkg-config
                brew install autoconf-archive
                brew install autoconf
                brew install automake
             fi
      - name: Install Dependencies
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install libicu-dev libxml2-dev libbz2-dev
                sudo apt-get install zlib1g-dev libtar-dev cppcheck
             else
                brew install libxml2;
                brew install bzip2;
                brew install zlib;
                brew install libtar
                brew install cppcheck
             fi
      - name: install TiccUtils
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          git clone https://github.com/LanguageMachines/ticcutils;
          cd ticcutils;
          bash bootstrap.sh;
          ./configure;
          make;
          sudo make install;
          cd ..;

      - name: bootstrap
        run: sh bootstrap.sh
      - name: configure
        env:
          CXX: ${{ matrix.compiler }}
        run: ./configure
      - name: compiler-id
        id: compiler
        run: |
          id=$(echo ${{matrix.compiler}} | cut -d\+ -f1)
          echo "::set-output name=id::$id"
      - name: Static Code-check
        run: cppcheck --enable=all --quiet --error-exitcode=0 .
      - name: make
        run: make
      - name: install
        run: sudo make install
      - name: make check
        env:
          CXX: ${{ matrix.compiler }}
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make check
        continue-on-error: true
      - name: show log
        run: cat src/test-suite.log
      - name: Notify IRC of failure
        if: ${{ failure() }}
        uses: Gottox/irc-message-action@v1
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GitHub-${{ runner.os }}-${{ steps.compiler.outputs.id }}
          message: |-
            Timbl [${{ steps.extract_branch.outputs.branch }}] build with ${{ matrix.compiler }} by ${{ github.actor }} on ${{ matrix.os }}: FAILED
      - name: Notify IRC of succes
        if: ${{ success() }}
        uses: Gottox/irc-message-action@v1
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GitHub-${{ runner.os }}-${{ steps.compiler.outputs.id }}
          message: |-
            Timbl [${{ steps.extract_branch.outputs.branch }}] build with ${{ matrix.compiler }} by ${{ github.actor }} on ${{ matrix.os }}: SUCCESS
